version: '2'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
        environment:
          - cluster.name=docker-cluster
        volumes:
          - esdata1:/usr/share/elasticsearch/data
        ports:
          - 9200:9200
        restart: always

    kibana:
      image: docker.elastic.co/kibana/kibana:6.5.4
      ports:
        - 5601:5601
      restart: always
      
volumes:
  esdata1:
    driver: local