name: textgen
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip=20.1.1
  - numpy=1.19.1
  - pandas=1.0.5
  - pip:
    - deidentify==0.6.0
    - elasticsearch<7
    - elasticsearch-dsl<7
    - flair==0.4.5
    - jsonlines==1.2.0
    - tqdm==4.48.0
    - spacy==2.3.1
    - torch==1.3.1
    - rouge_score==0.0.4
    - https://github.com/explosion/spacy-models/releases/download/nl_core_news_sm-2.2.1/nl_core_news_sm-2.2.1.tar.gz#egg=nl_core_news_sm==2.2.1
